# Site settings
name: rory0114
email: 360821606@qq.com
author: liyanrui
url: https://github.com/rory0114
resume_site: https://github.com/rory0114//Resume.io/
github: https://github.com/rory0114/
baseurl: ''
description: Actually, less is more!
meta_description: 李彦瑞;个人博客;生命潦草，我在弯腰；历史轮回，转身忘掉
motto: not now；
banner: hellow world

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: rory0114

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

